create database customer_behaviour;
use customer_behaviour;
select * from customer limit 20;

#1Q.What is the total revenue generated by male vs female customers?
ALTER TABLE customer 
CHANGE COLUMN `purchase_amount_(usd)` purchase_amount DECIMAL(10,2);

select gender,sum(purchase_amount) as Total_Revenue from customer
group by gender;

#2Q.Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from customer
where discount_Applied ='Yes' 
and 
purchase_amount>= (Select avg(purchase_amount) from customer);

#3Q.Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),1) as AVG_Product_RATING from customer 
group by item_purchased
order by AVG_product_RATING desc
limit 5;

#4Q.Compare the average purchase amounts between standard and express shipping

select shipping_type,round(avg(purchase_Amount),2) as avg_purchase_amt from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

#5Q.Do subscribed customers spend more? Compare avg spend and total revenue between subscribers and non-subscribers.

select subscription_status,count(customer_id) as Total_Customers,sum(purchase_amount) as Total_revenue,round(avg(purchase_amount),2) as Avg_spend
from customer
group by subscription_status
order by Total_Revenue and Avg_spend desc;

#6Q.Which 5 products have the highest percentage of purchases with discount applied?

select item_purchased,
ROUND(100*sum(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2)AS DISCOUNT_RATE
from customer
group by item_purchased
order by DISCOUNT_RATE DESC
LIMIT 5;

#7Q.Segment customers into New,Returning and Loyal based on their total number of previous purchases and show the count of each segment.

with customer_Type as(
select customer_id,previous_purchases,
CASE 
  WHEN previous_purchases=1 THEN 'New'
  WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
  ELSE 'Loyal'
  END AS customer_Segment
from customer)

select customer_Segment,count(*) as 'Number_of_customers'
from customer_type
group by customer_segment;

#8Q.What are the top 3 most purchased products within each category?

With item_counts as(
select category,
item_purchased,
count(customer_id) as Total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category,item_purchased)

select item_rank,category,item_purchased,Total_orders
from item_counts
where item_rank <=3;

#9Q.Customers who are repeate buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

#10Q. What is the revenue contribution of each age group? 

SELECT age_group,SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;
